### PR TITLE
Make the NBT-API compatible with Forge 1.7.10

### PR DESCRIPTION
**Pull request by EverNife**
Solves https://github.com/tr7zw/Item-NBT-API/issues/170

-----------------------------

I tried to keep the lesser amount of changes as possible.

### CODE REVIEW

**Comment by tr7zw** [comment]
Huh, thats a new one, but I guess with the new 1.18 obfuscation logic, it is possible to add Crucible Forge mappings. I'll have to take a look at it, but at a glance, it looks good.

**Comment by tr7zw** [comment]
Oops kinda forgot about this one, I'll work on merging it when spigot 1.19 pre releases are out.

**Comment by EverNife** [comment]
> Oops kinda forgot about this one, I'll work on merging it when spigot 1.19 pre releases are out.

me too, i will undo my commit '-'

**Comment by tr7zw** [comment]
Just randomly got the message on discord that there was a new commit, and a clear all doesn't sound like a bad idea. Yesterday we encountered a huge bug/issue/oversight on spigots end with nbt and itemstack cloning, so that will have to be addressed too in the next release.

**Comment by EverNife** [comment]
Ty, i will let it them :D

**Comment by tr7zw** [comment]
@EverNife Just got made aware that at least spigot/craftbukkit 1.7.10 sometimes just loses all custom nbt when switching the item around in the inventory. Now I'm thinking about removing the entire 1.7.10 legacy parts from the plugin, since according to bStats there are only about 1000 1.7 servers in the world total anyway, and nobody notices this critical 1.7 bug in the past 7.5 years. Or is there some sane workaround for this behavior?

**Comment by EverNife** [comment]
Sorry for the late reply. As a legacy developer, i am already pretty grantefull that the api supported 1.7.10 so far!

It should be ok to stop giving support as of now.

About those 1.7.10 bugs you said. 1.7.10 mainly works with mods!
Most of these bugs are already fixed on custom forge builds like Thermos/Crucible.

**Comment by tr7zw** [comment]
Huh, so it does work for this use case(or technically in general), but on normal spigot/paper 1.7 the nbt changes just vanish from time to time. Might be an idea to just pin 1.7 support to one last version(so if one wants to use 1.7, just use version x for that, since nothing changes anyway).

**Comment by EverNife** [comment]
Seems pretty good :D

**Comment by Worf2340** [comment]
> Might be an idea to just pin 1.7 support to one last version(so if one wants to use 1.7, just use version x for that, since nothing changes anyway).

Did this ever get done? I'm looking for the last version to support 1.7.

**Comment by EverNife** [comment]
> Did this ever get done? I'm looking for the last version to support 1.7.10 Forge.

I think is this one:

image


https://www.spigotmc.org/resources/nbt-api.7939/history

**Comment by tr7zw** [comment]
The 2.11.1 version also still contains all the 1.7 code, haven't yet removed it.

**Comment by tr7zw** [comment]
Also just had to check where that 1-star review comes from... Someone has a plugin that contains the nbtapi(probably an old version) and then tells me that it's self-installing onto his server or something. Correct reaction:
a) Ask on Github
b) Ask on Discord
c) Make a 1 star review on an unrelated project ✅

**Comment by EverNife** [comment]
Your plugin is probably one of the most integrated plugin around.
Many devs use your plugin integrated on their own.

Users are crazy :/

**Pull request merged**
