### PR TITLE
Use Mojang Mappings for fabric mod (3.0-Indev)

### PR DESCRIPTION
**Pull request by Toffikk**

### CODE REVIEW

**Comment by spnda** [comment]
I feel like the bump to loom 0.9 is good but I'm not sure if Mojang mappings are any better than yarn mappings and if there are any benefits of using one over the other.

**Comment by Toffikk** [comment]
The forge version uses mojang mappings too, I think it’s better to use the same mappings where possible instead of using different mappings

**Comment by tr7zw** [comment]
This is actually really cool. I wasn't aware that loom has that option, and I was already looking some time ago on how to get forge to use loom/fabric to use mojang mappings.
This would basically mean that you can use spigot, fabric and forge, all with Mojang mappings, and thereby reuse nearly all nms code between them. Also, reaaaaallly helpful for my projects like TRansliterationLib.
Thanks for making me aware of this, and yea after giving it a try, I'll probably accept the pr and with 1.17+ switch to pure Mojang mappings.

**Comment by spnda** [comment]
> I wasn't aware that loom has that option

Yeah, it got recently introduced with loom 0.9 just a few weeks ago. I think it was introduced to also support https://parchmentmc.org and in the future also projects with layered mappings.

**Pull request merged**
