### PR TITLE
Implemented option to turn off logging

### PR DESCRIPTION
**Pull request by Chazza**
Hi,

As I felt the logging could be too much, I created a simple switch to turn this on/off as needed. I feel this could be useful for the developers that want to only turn it on in a 'debug' command.

Thanks.

### CODE REVIEW

**Comment by Chazza** [comment]
It'll be set to log by default, however by using:
`MinecraftVersion.setLogging(false);`

It'll be silencing from logs, which personally I find as a cleaner approach.

**Comment by Chazza** [comment]
I've introduced an optional logging system which stays persistent - yet easily to modify where needed.

Developers may type `NBTAPI.setLogging(false);` on enable to hide NBT messages, or turn it on if they desire.

**Comment by tr7zw** [comment]
Right now this would only allow disabling the one line that shows up when loading the plugin/using the plugin for the first time. Not sure where this really would be useful? Maybe would be more interesting to fix the logging of the project in general and having "disable non error output" as an option.

**Comment by Chazza** [comment]
@tr7zw this appears multiple times for me, my plugin creates a new NBTItem and that logs out every time which can become spammy.

This was the reason I ended up forking your project and making those changes, so that I could hide the console spam.

**Comment by tr7zw** [comment]
This message can only show up once, or it's an error on your end like constantly reloading the plugin. On the first call to this method a fitting version is searched and put into a static field. As long as that field is not null, it won't show this message anymore. My only guess is reloading the server/single plugin reloading that could cause this to reset.

**Comment by tr7zw** [comment]
Nothing new seems to show up. It was probably Pluginman or something, reloading the api. Please reopen an issue if this still keeps happening(especially with version 2.0).

**Pull request closed without merging**
